declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_GITHUB_API_BASE_URL: string
    NEXT_PUBLIC_APP_NAME: string
    NEXT_PUBLIC_DEFAULT_PER_PAGE: string
    NEXT_PUBLIC_MAX_PER_PAGE: string
    NEXT_PUBLIC_MIN_REQUEST_INTERVAL: string
    NEXT_PUBLIC_API_TIMEOUT: string
    NEXT_PUBLIC_SEARCH_DEBOUNCE_DELAY: string
    NEXT_PUBLIC_QUERY_STALE_TIME: string
    NEXT_PUBLIC_QUERY_GC_TIME: string
    NEXT_PUBLIC_QUERY_RETRY_COUNT: string
    NEXT_PUBLIC_QUERY_RETRY_DELAY_BASE: string
    NEXT_PUBLIC_QUERY_RETRY_DELAY_MAX: string
    NEXT_PUBLIC_REPOSITORY_DETAILS_STALE_TIME: string
    NEXT_PUBLIC_REPOSITORY_DETAILS_RETRY_COUNT: string
    NEXT_PUBLIC_DEFAULT_FORK_COUNT: string
    NEXT_PUBLIC_MAX_FILE_TYPES: string
  }
}